module.exports = class Data1677850568670 {
    name = 'Data1677850568670'

    async up(db) {
        await db.query(`CREATE TABLE "cumulative_dex_trading_volume_per_account" ("id" character varying NOT NULL, "account_id" text NOT NULL, "till_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "amounts" jsonb NOT NULL, CONSTRAINT "PK_014a93ec80c000241591ebb7d1e" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_d8cca4aa75481cbef78c0fabae" ON "cumulative_dex_trading_volume_per_account" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_8d4d104d3fdda735ad959c7547" ON "cumulative_dex_trading_volume_per_account" ("till_timestamp") `)
        await db.query(`CREATE TABLE "cumulative_dex_trading_volume" ("id" character varying NOT NULL, "till_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "amounts" jsonb NOT NULL, CONSTRAINT "PK_283cec7156272ed6a2403934d6a" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_17d4754307c61f823d98896a11" ON "cumulative_dex_trading_volume" ("till_timestamp") `)
        await db.query(`CREATE TABLE "cumulative_dex_trade_count_per_account" ("id" character varying NOT NULL, "account_id" text NOT NULL, "till_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "count" numeric NOT NULL, CONSTRAINT "PK_3b45eb895406ab041f12f2965b3" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_f20b922f56a98fd0483e4ba0d6" ON "cumulative_dex_trade_count_per_account" ("account_id") `)
        await db.query(`CREATE INDEX "IDX_5f872c3cc3aa04df58b3288fd9" ON "cumulative_dex_trade_count_per_account" ("till_timestamp") `)
        await db.query(`CREATE TABLE "cumulative_dex_trade_count" ("id" character varying NOT NULL, "till_timestamp" TIMESTAMP WITH TIME ZONE NOT NULL, "count" numeric NOT NULL, CONSTRAINT "PK_28f693c012e905438b6b1d80d77" PRIMARY KEY ("id"))`)
        await db.query(`CREATE INDEX "IDX_4086e8663faeb3eabc1f8fb0ea" ON "cumulative_dex_trade_count" ("till_timestamp") `)
        await db.query(`ALTER TABLE "loan_market" DROP COLUMN "currency_symbol"`)
        await db.query(`ALTER TABLE "loan" DROP COLUMN "amount_borrowed_usdt"`)
        await db.query(`ALTER TABLE "loan" DROP COLUMN "amount_borrowed_btc"`)
        await db.query(`ALTER TABLE "loan" DROP COLUMN "amount_repaid_usdt"`)
        await db.query(`ALTER TABLE "loan" DROP COLUMN "amount_repaid_btc"`)
        await db.query(`ALTER TABLE "loan" DROP COLUMN "currency_symbol"`)
        await db.query(`ALTER TABLE "deposit" DROP COLUMN "symbol"`)
        await db.query(`ALTER TABLE "deposit" DROP COLUMN "type"`)
        await db.query(`ALTER TABLE "deposit" DROP COLUMN "amount_deposited_usdt"`)
        await db.query(`ALTER TABLE "deposit" DROP COLUMN "amount_deposited_btc"`)
        await db.query(`ALTER TABLE "deposit" DROP COLUMN "amount_withdrawn_usdt"`)
        await db.query(`ALTER TABLE "deposit" DROP COLUMN "amount_withdrawn_btc"`)
        await db.query(`ALTER TABLE "deposit" DROP COLUMN "currency_symbol"`)
    }

    async down(db) {
        await db.query(`DROP TABLE "cumulative_dex_trading_volume_per_account"`)
        await db.query(`DROP INDEX "public"."IDX_d8cca4aa75481cbef78c0fabae"`)
        await db.query(`DROP INDEX "public"."IDX_8d4d104d3fdda735ad959c7547"`)
        await db.query(`DROP TABLE "cumulative_dex_trading_volume"`)
        await db.query(`DROP INDEX "public"."IDX_17d4754307c61f823d98896a11"`)
        await db.query(`DROP TABLE "cumulative_dex_trade_count_per_account"`)
        await db.query(`DROP INDEX "public"."IDX_f20b922f56a98fd0483e4ba0d6"`)
        await db.query(`DROP INDEX "public"."IDX_5f872c3cc3aa04df58b3288fd9"`)
        await db.query(`DROP TABLE "cumulative_dex_trade_count"`)
        await db.query(`DROP INDEX "public"."IDX_4086e8663faeb3eabc1f8fb0ea"`)
        await db.query(`ALTER TABLE "loan_market" ADD "currency_symbol" text NOT NULL`)
        await db.query(`ALTER TABLE "loan" ADD "amount_borrowed_usdt" numeric`)
        await db.query(`ALTER TABLE "loan" ADD "amount_borrowed_btc" numeric`)
        await db.query(`ALTER TABLE "loan" ADD "amount_repaid_usdt" numeric`)
        await db.query(`ALTER TABLE "loan" ADD "amount_repaid_btc" numeric`)
        await db.query(`ALTER TABLE "loan" ADD "currency_symbol" text NOT NULL`)
        await db.query(`ALTER TABLE "deposit" ADD "symbol" text NOT NULL`)
        await db.query(`ALTER TABLE "deposit" ADD "type" text NOT NULL`)
        await db.query(`ALTER TABLE "deposit" ADD "amount_deposited_usdt" numeric`)
        await db.query(`ALTER TABLE "deposit" ADD "amount_deposited_btc" numeric`)
        await db.query(`ALTER TABLE "deposit" ADD "amount_withdrawn_usdt" numeric`)
        await db.query(`ALTER TABLE "deposit" ADD "amount_withdrawn_btc" numeric`)
        await db.query(`ALTER TABLE "deposit" ADD "currency_symbol" text NOT NULL`)
    }
}
